"""File for Car class and its complements."""
from abc import ABC, abstractmethod
from logging import Logger, getLogger
from enum import Enum
from typing import Type

log: Logger = getLogger(__name__)

from driving_cli.entities.abstracts.abstract_transmission import ATransmission
from driving_cli.entities.abstracts.abstract_throttle import AThrottle
from driving_cli.entities.abstracts.abstract_brake import ABrake
from driving_cli.entities.abstracts.abstract_engine import AEngine
from driving_cli.entities.abstracts.abstract_energy_provider import AEnergyProvider
from driving_cli.use_cases.validators import clamp_value



class AVehicle(ABC):
    """
    Abstract vehicle class.
    """
    _weight: float = 0.0
    _speed: float = 0.0
    _acceleration: float = 0.0
    _mechanical_horse_power: float = 0.0
    _mechanical_power_watts: float = 0.0
    _throttle: AThrottle = None
    _brake: ABrake = None
    _engine: AEngine = None
    _energy_provider: Type[AEnergyProvider] = None
    _transmission: ATransmission = None
    WATTS_PER_HORSEPOWER = 745.7

    class Constants(Enum):
        SPEED_MAX = 500.0
        SPEED_MIN = 0.0
        ACCELERATION_MAX = 1.0
        ACCELERATION_MIN = 0.0
        MECHANICAL_HORSE_POWER = 0.0
        MECHANICAL_POWER_WATTS_MAX = 0.0
        MECHANICAL_POWER_WATTS_MIN = 0.0

    @property
    def speed(self) -> float:
        return self._speed

    @property
    def mechanical_power_watts(self) -> float:
        """Calculates the instantaneous mechanical power generated by the engine in Watts."""
        current_force: float = self.engine.force
        current_speed: float = self.speed
        power_watts: float = current_force * current_speed

        return power_watts

    @property
    def mechanical_horsepower(self) -> float:
        """Calculates the instantaneous mechanical power in Horsepower"""
        power_watts = self.mechanical_power_watts
        power_hp: float = power_watts / self.WATTS_PER_HORSEPOWER

        return power_hp

    @property
    def acceleration(self) -> float:
        if self.weight <= 0:
            log.warning("Invalid weight: %s", self.weight)
            return 0.0
        #effective_force = self.engine.force - frictions
        effective_force = self.engine.force
        raw_acceleration: float = effective_force / self.weight
        self._acceleration =  clamp_value(value=raw_acceleration,
                                          min_value=self.Constants.ACCELERATION_MIN.value,
                                          max_value=self.Constants.ACCELERATION_MAX.value,
                                          name="Acceleration"
                                          )
        return self._acceleration

    @property
    def throttle(self) -> AThrottle:
        return self._throttle

    @property
    def brake(self) -> ABrake:
        return self._brake

    @property
    def engine(self) -> AEngine:
        return self._engine

    @property
    def energy_provider(self) -> Type[AEnergyProvider]:
        return self._energy_provider

    @property
    def transmission(self) -> ATransmission:
        return self._transmission

    @property
    def weight(self) -> float:
        """Sum of weight of vehicle part."""
        return self._weight

    def __init__(self, throttle: AThrottle,
                 brake: ABrake,
                 engine: AEngine,
                 energy_provider: Type[AEnergyProvider],
                 transmission: ATransmission):
        self._throttle: AThrottle = throttle
        self._brake: ABrake = brake
        self._engine: AEngine = engine
        self._energy_provider: Type[AEnergyProvider] = energy_provider
        self._transmission: ATransmission = transmission
        self._weight: float = (self.throttle.weight +
                               self.brake.weight +
                               self.engine.weight +
                               self.energy_provider.weight)
        self._speed: float = 0

    # classify_by_weight()
    # vehicle_types

    def constants(self):
        return self.Constants


    def increase_throttle(self) -> None:
        """Increases vehicle throttle instance throttle value and resets brake."""
        self._brake.reset_brake()
        self._throttle.increase_throttle()


    def decrease_throttle(self) -> None:
        """Increases vehicle throttle instance throttle value."""
        self._throttle.decrease_throttle()


    def engage_brake(self) -> None:
        """Increase vehicle brake instance brake value and reset throttle."""
        self._throttle.reset_throttle()
        self._brake.engage_brake()


    def disengage_brake(self) -> None:
        """Decrease vehicle brake instance brake value."""
        self._brake.disengage_brake()

    # @abstractmethod
    # def drive(self) -> None:
    #     """Subclasses must implement driving logic."""
    #     pass

    def accelerate(self) -> None:
        """Increases speed using throttle and engine force and gear_ratio."""
        gear_ratio: float = self._transmission.ratio
        throttle_value: float = self._throttle.throttle_value
        self._engine.increase_power_output(throttle_value, gear_ratio)
        new_speed: float = self._acceleration + self._speed
        self._speed = clamp_value(value=new_speed,
                                  min_value=self.Constants.SPEED_MIN.value,
                                  max_value=self.Constants.SPEED_MAX.value,
                                  name="Speed"
                                  )

    # @abstractmethod
    # def hamper_by_frictions(self) -> None:
    #     """Reduces speed due to natural forces when engine force is not actively overcoming them."""
    #     # friction, drag
    #     pass


    def hamper_by_brake(self) -> None:
        """Reduce speed according to brake intensity."""
        delta = max(self._speed - self._brake.brake_value * self._brake.effectiveness, 0.0)
        self._speed = clamp_value(value=delta,
                                  min_value=self.Constants.SPEED_MIN.value,
                                  max_value=self.Constants.SPEED_MAX.value,
                                  name="Speed"
                                  )


    def decrease_energy_volume(self):
        """Reduces volume of energy provider by engine combustion."""
        log.info("Decreasing energy volume")
        value: float = min(self._energy_provider.volume - self._engine.combustion, 0.0)
        self._energy_provider.volume = value
